### ISSUE TITLE
Whitelist

### ISSUE THREAD

**Issue by tawheeler** [sisl/Draftcheck.jl#1]
Draftcheck can produce a large number of false positives, or known issues that we would like to ignore.

One convenient way that tools like code linters handle this is a whitelist, which lists lines that can be ignored. Such a list can be automatically generated by the program (since it generates the errors) and if the line in question has been changed, it should re-trigger the warning. 

This helps developers see what _new_ lint errors have been introduced, rather than having to wade through a large list of known issues.

**Comment by mykelk** [comment]
I think this is already implemented. See README.md. You can do it as a comment, e.g., `# OK times`. Is this what you had in mind?

**Comment by tawheeler** [comment]
I don't want to manually add 100 comments, nor have draftcheck modify my LaTeX file. I want to effectively load those ignores into a file.

**Comment by tawheeler** [comment]
A clang-tidy whitelist yaml file looks like this:
```yaml
- column: '17'
  message: missing username/bug in TODO
  path: potato/my_cool_code.cpp
  snippet: '                // TODO: Should probably do nothing rather than 0.0.'
- column: '17'
  message: statement should be inside braces
  path: lib/external/more_code.cpp
  snippet: '    if (reg_int)'
```

for us it could be:
```yaml
- rule: multiply
  message: When multiplying, do not use 'x'.
  path: chapter/that_chapter.tex
  snippet: 'c = A*b # 3x3 matrix'
```
